name: "Dingtalk pull request notify"
description: "A dingtalk pull request notify of GitHub actions."
author: "zhecks"
inputs:
  notification_title:
    required: false
    description: "the title of notification"
    default: "${{ github.repository }}"
  
  token:
    required: false
    description: "it's neccessary for private repository, public repository also can use token to increase api's limit"

  users:
    required: true
    description: "the user mapping to the dingtalk's phone number, e.g. Alice|150xxxx,Bob|139xxxx"
  
  reviewers:
    required: true
    description: "the reviewer, e.g. phone1,phone2"

  timeout:
    required: false
    description: "the timeout time which wait for other workflows"
    default: "600"

  interval:
    required: false
    description: "the interval of polling"
    default: "15"

  webhook:
    required: true
    description: "the dingtalk robot's webhook"
  
  job_name:
    required: false
    description: "the job name "
    default: "Dingtalk notify"

runs:
  using: "node16"
  main: "dist/index.js"
